### ISSUE TITLE
Allow execution of a transaction via the mock

### ISSUE THREAD

**Issue by rmeissner** [safe-global/mock-contract#5]
For setting up the mock contract with other contract it is sometimes required to trigger a transaction via the mock. For this it would be good to add a method and utils that allow execution of a transaction via the mock.

An example for this can be found [here](https://github.com/5afe/safe-core-protocol-demo/blob/main/contracts/contracts/Imports.sol#L10-L19)

It would be nice to add the possibility for delegate calls to make it more flexible.

Sub-tasks:
- [x] Add `executeCallViaMock` with `to`, `value`, `data`, `gas` to the mock contract
- [x] Add `executeDelegatecallViaMock` with `to`, `data`, `gas` to the mock contract

Open questions:
- Should the usage of the method be safeguarded (i.e. only be available to the deployer of the mock contract).

**Comment by akshay-ap** [comment]
As this is a mock contract, I think it should not implement any safeguarding logic.

**Comment by rmeissner** [comment]
Maybe safeguarding was the wrong word. The purpose was not to limit who can call it for security, but rather to avoid that there is a conflict during a test setup (i.e. you want to check if a method with the same function selector is called on the mock contract).

**Comment by akshay-ap** [comment]
@rmeissner Can you provide a final preference from these below:
a. Current implementation
b. No safeguarding
c. Set flags in constructor of the `MockContract` https://github.com/safe-global/mock-contract/commit/221972c7b3d3d1ee48dd1e3eec604d2cbc90cb58
d. Create another contract `MockContractWithCall` and combine with `b`
e. Create another contract `MockContractWithCall` and combine with `c`

**Comment by akshay-ap** [comment]
Updated implementation to option `d`. 
Readme will be updated in #6
